// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace As.Entity
{
    public partial class Location
    {
        public Location()
        {
            Student = new HashSet<Student>();
        }

        [Key]
        public int LocationId { get; set; }
        [Column("Location")]
        [StringLength(50)]
        [Unicode(false)]
        public string Location1 { get; set; }
        public bool Is_Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Create_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time_Stamp { get; set; }

        [InverseProperty("Location")]
        public virtual ICollection<Student> Student { get; set; }
    }
}