// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace As.Entity
{
    public partial class Student
    {
        [Key]
        public int StudentId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string LastName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Department { get; set; }
        public int? Age { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Class { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Gender { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string YearOfJoining { get; set; }
        public int LocationId { get; set; }
        public bool Is_Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Create_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time_Stamp { get; set; }

        [ForeignKey("LocationId")]
        [InverseProperty("Student")]
        public virtual Location Location { get; set; }
    }
}